# -*- coding: utf-8 -*-
"""PDF rename.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZvXCHFW0mncaYw5l9kcC39cWT9TWxOH9

# **PDF rename**

***Step 0:***
Put all pdf that needed to be renamed into a zip file

Create an empty zip file called "renamed.zip"

**Step 1:**
Package Installation

(The following install syntax works for Google Colab)
"""

#pip install pdfrw
from pdfrw import PdfReader
from zipfile import ZipFile
from pathlib import Path
import os
import glob


THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))
Filename = os.path.join(THIS_FOLDER, 'target.zip')
renamedfilename =os.path.join(THIS_FOLDER, 'renamed.zip')
"""**Step 2:**
Determine new names

Change Filename to the zip file name you are working with
"""

# Change Filename below to the zip file name you are working with
#Filename = '/Users/catina/Desktop/pdf_rename/target.zip'

# Determine new name

from os import walk
mypath = THIS_FOLDER + '/target'
f = []
d = []
for (dirpath, dirnames, filenames) in walk(mypath):
    f.extend(filenames)
f.remove('.DS_Store')
for file in f:
    d.append(THIS_FOLDER + '/target/'+file)
print(f)
print(d)

#file_path =THIS_FOLDER + "*.pdf"
#files_list = glob.glob(file_path)

#z = ZipFile(Filename)
newnames = []
for i in range(len(f)):
  #text = file.filename
  #file_name = text.split('/', 1)[1]
 # print(d[i])
  reader = PdfReader(d[i])
  #print("2")
  title=''
  author=''
  date=''
  if str(type(reader.Info.Title)) != "<class 'NoneType'>":
    title= reader.Info.Title[1:len(reader.Info.Title)-1]
    print(title)
  if str(type(reader.Info.Author)) != "<class 'NoneType'>":
    author = reader.Info.Author[1:len(reader.Info.Author)-1]
    words = author. split()
    lastname = words[-1]
    print(lastname)
  if str(type(reader.Info.CreationDate)) != "<class 'NoneType'>":
    date = reader.Info.CreationDate[3:7]
    print(date)
  new_name = title +'|' + author + '|' + date +'.pdf'
  print(new_name)
  newnames.append(THIS_FOLDER + '/target/'+new_name)
count=0

"""New file names"""

print(newnames)

for i in range(len(f)):
  os.rename(d[i],newnames[i])

"""Create new zip file with renamed pdf"""

#source = ZipFile(Filename, 'r')
#target = ZipFile(renamedfilename, 'w')
#for file in source.filelist:
#  target.writestr(newnames[count], source.read(file.filename))
#  count +=1
#target.close()
#source.close()
